spring.application.name: consumer-app

kafka:
  bootstrap-servers: localhost:9092
  consumer:
    enable-auto-commit: false
    auto-offset-reset: earliest
    max-poll-records: 5
    group-id: consumer-app
    client-id: consumer-app

topics:
  jaeger-topic: tracing-topic
  source-topic: sentence-topic
  target-topic: answer-topic
