spring:
  application.name: spring-consumer-app
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      enable-auto-commit: false
      auto-offset-reset: earliest
      group-id: spring-consumer-app
      client-id: spring-consumer-app

topics:
  jaeger-topic: tracing-topic
  source-topic: even-topic
  target-topic: sentence-topic

rest-app:
  url: http://localhost:8096
  api: /random